n1= float(input("Digite o primeiro número: "));
n2= float(input("Digite o segundo número: "));
comp1= n1 == n2;
comp2= n1 >= n2;
comp3= n1 <= n2;
comp4= n1 > n2;
comp5= n1 < n2;
comp6= n1 != n2;
print(n1, "==", n2, "?", comp1);
print(n1, ">=", n2, "?", comp2);
print(n1, "<=", n2, "?", comp3);
print(n1, ">", n2, "?", comp4);
print(n1, "<", n2, "?", comp5);
print(n1, "=!", n2, "?", comp6);
